@startuml 3
actor Usuario
participant Sistema
participant "Banco de Dados" as BD

Usuario -> Sistema : informarDadosCadastro(dados)
Sistema -> Sistema : validarInformacoes()
create "Novo Usuario" as UserObj
Sistema -> UserObj : criar()
Sistema -> BD : salvar(UserObj)
BD --> Sistema : confirmacaoSalvo
Sistema --> Usuario : cadastroRealizado
@enduml